# Generated by Django 4.0.2 on 2022-02-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100, unique=True)),
                ('segment', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('monthly_revenue', models.FloatField()),
                ('money_purpose', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('installments', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id_offer', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('amount_perc', models.FloatField()),
                ('interest', models.FloatField()),
                ('tax_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditProposal',
            fields=[
                ('id_proposal', models.AutoField(primary_key=True, serialize=False)),
                ('id_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('offers', models.ManyToManyField(to='api.Offer')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='chosen_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offer'),
        ),
    ]
